### PR TITLE
Add fix for youtube

### LINKED ISSUE #53: Extension doesn't work for youtube

### PR DESCRIPTION
**Pull request by Kaboomboom3**
Closes #53

### CODE REVIEW

File: js/content.js [hunk 1]
```diff
@@ -239,12 +247,12 @@ function addCheckmark() {
...
-    fadeOut(checkElement); 
-    fadeOut(para); 
+    fadeOut(checkElement);
+    fadeOut(para);
     fadeOut(divContainer);
-    // resets the website after all the fading has occurred 
+    // resets the website after all the fading has occurred
     setTimeout(() => {
-        console.log("gettingtotimeout"); 
+        console.log("gettingtotimeout");
```
Comment (mmattikalli) [inline js/content.js]: is the console log taken out?
