### PR TITLE
Fix facelock.js erroring when tab does not switch

### LINKED ISSUE #38: Background script errors when lock is disabled if tab does not switch
Caused by commit: e47702a3cc5f3370576ecf7cffd85d077f5ec1ef

### PR DESCRIPTION
**Pull request by Kaboomboom3**
Closes #38

### CODE REVIEW

File: js/facelock.js [hunk 1]
```diff
@@ -98,26 +86,22 @@ function tabSwitchHandler(activeInfo) {
 }
 
 function setupTab(tabId) {
```
Comment (ThatOneGoat) [inline js/facelock.js]: Add comments for methods down below
